networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: rw
      device: /mnt/over_todo/db/data
      o: bind
  api_data:
    driver: local
    driver_opts:
      type: rw
      device: /mnt/over_todo/api/data
      o: bind

services:
  db:
    networks:
      - backend
    build:
      context: backend/src/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}
    restart: always
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    networks:
      - backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: 4000
    expose:
      - 4000

  gateway:
    depends_on:
      - api
    networks:
      - frontend
      - backend
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:80"